name: Go lang with Docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Build the Docker image
      #env:
        #IMAGE_TAG: $$(git log -1 --pretty=%!H(MISSING))
      run: docker build . --file Dockerfile --tag sdthiruma/demo-apps:1.0.${{ github.run_number }}
    
    - name: Docker login
      env:
        DOCKER_USER:  ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
 
    - name: Push the Docker image to Docker hub
      run: docker push sdthiruma/demo-apps:1.0.${{ github.run_number }}
